// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgraasApi.Data;

#nullable disable

namespace OgraasApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230523071949_all models added")]
    partial class allmodelsadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgraasApi.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("OgraasApi.Models.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHit")
                        .HasColumnType("bit");

                    b.Property<int?>("WeedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeedId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("OgraasApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("OgraasApi.Models.Weed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Weeds");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Weed");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OgraasApi.Models.Kardborre", b =>
                {
                    b.HasBaseType("OgraasApi.Models.Weed");

                    b.HasDiscriminator().HasValue("Kardborre");
                });

            modelBuilder.Entity("OgraasApi.Models.Kirskal", b =>
                {
                    b.HasBaseType("OgraasApi.Models.Weed");

                    b.HasDiscriminator().HasValue("Kirskal");
                });

            modelBuilder.Entity("OgraasApi.Models.Kvickrot", b =>
                {
                    b.HasBaseType("OgraasApi.Models.Weed");

                    b.HasDiscriminator().HasValue("Kvickrot");
                });

            modelBuilder.Entity("OgraasApi.Models.Maskros", b =>
                {
                    b.HasBaseType("OgraasApi.Models.Weed");

                    b.HasDiscriminator().HasValue("Maskros");
                });

            modelBuilder.Entity("OgraasApi.Models.Cell", b =>
                {
                    b.HasOne("OgraasApi.Models.Weed", "Weed")
                        .WithMany()
                        .HasForeignKey("WeedId");

                    b.Navigation("Weed");
                });
#pragma warning restore 612, 618
        }
    }
}
